version: 2
registries:
    dockerhub:
        type: docker-registry
        url: https://registry.hub.docker.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    dhi:
        type: docker-registry
        url: https://dhi.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
      ignore:
          # Ignore non-LTS Django updates
          - dependency-name: "django"
            versions: [">= 6.0, < 6.2", ">= 7.0, < 7.2"]

    - package-ecosystem: "bun"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7

    - package-ecosystem: "docker"
      registries:
          - dhi
          - dockerhub
      directories:
          - "/"
          - "/ghost"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
      ignore:
          - dependency-name: "postgres"

    - package-ecosystem: "docker-compose"
      registries:
          - dhi
          - dockerhub
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
      ignore:
          - dependency-name: "postgres"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
