version: 2
registries:
  docker-registry:
    type: docker-registry
    url: https://dhi.io
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}
    replaces-base: true
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7

    - package-ecosystem: "bun"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7

    - package-ecosystem: "docker-compose"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
