services:
    nginx:
        image: nginx:1.27
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            # Media and static files
            - ./app/static/app:/static/app
            - ./rest/static/rest:/static/rest
            - ./data:/data
        depends_on:
            - web

    web:
        build: .
        restart: always
        env_file: [.env]
        # Automatically runs makemigrations + migrate to update Django models
        command: >
            /bin/bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        expose:
            - 8000
        volumes:
            # Update Django files in real-time
            - .:/usr/src/app
            # Media and static files
            - ./app/static/app:/usr/src/app/static/app
            - ./rest/static/rest:/usr/src/app/static/rest
            - ./data:/usr/src/app/data
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres
        restart: always
        env_file: [.env]
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    db_data:
