services:
    nginx:
        image: nginx:1.27
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            # Media and static files
            - static_files:/static
            - ./data:/data
        depends_on:
            - web
            - ghost

    ghost:
        build: ./ghost
        environment:
            - database__client=mysql
            - database__connection__host=mysql
            - database__connection__user=root
            - database__connection__password=example
            - database__connection__database=ghost
            - url=http://localhost/blog/
        expose:
            - "2368"
        volumes:
            - ghost:/var/lib/ghost/content
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: ghost
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s

    web:
        build: .
        restart: always
        env_file: [.env]
        # Collect static files and update Django models
        command: >
            /bin/bash -c "python manage.py collectstatic --noinput
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        expose:
            - 8000
        volumes:
            # Update Django files in real-time
            - .:/usr/src/app
            # Media and static files
            - static_files:/usr/src/app/static
            - ./data:/usr/src/app/data
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres
        restart: always
        env_file: [.env]
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    ghost:
    mysql:
    db_data:
    static_files:
