# Production specific changes
services:
    web:
        # Automatically runs migrate to update Django models
        command: >
            /bin/bash -c "python manage.py migrate
            && gunicorn -w 4 config.wsgi --bind 0.0.0.0:8000"
        env_file:
            - .env
            - .env.prod
