services:
    web:
        build: .
        restart: always
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - ".:/usr/src/app"
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy

    # To properly setup Django with Postgres, we need to run these commands:
    #   docker compose up -d
    #   docker compose exec web python manage.py migrate
    #   docker compose exec web python manage.py createsuperuser
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
            POSTGRES_PASSWORD: mypassword
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    db_data:
