services:
    web:
        build: .
        restart: always
        # Automatically runs migrate in case of changes to Django models
        command: >
            /bin/bash -c "python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        # Mount volume on the current directory to live update Django files
        volumes:
            - ".:/usr/src/app"
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
            POSTGRES_PASSWORD: mypassword
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    db_data:
