# Generated by Django 5.2.8 on 2025-11-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dataset_options_alter_domain_options_and_more_squashed_0009_alter_datasetqualitycontrol_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='SpeciesFile',
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('checksum', models.CharField(editable=False, help_text='SHA256 digest.', max_length=64)),
                ('file', models.FileField(help_text='File.', upload_to='')),
                ('type', models.CharField(choices=[('singlecell_umifrac', 'singlecell_umifrac')], help_text='File type.', max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'type')},
            },
        ),
    ]
