# Generated by Django 5.2.8 on 2025-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_datasetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleCellGeneExpressionF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=200)),
                ('gene', models.CharField(max_length=200)),
                ('single_cell', models.CharField(max_length=200)),
                ('umifrac', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'single-cell gene expression',
                'verbose_name_plural': 'single-cell gene expression',
                'managed': False,
            },
        ),
    ]
