# Generated by Django 5.2.8 on 2025-11-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_datasetfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlecellgeneexpression',
            options={'managed': False, 'verbose_name': 'single-cell gene expression', 'verbose_name_plural': 'single-cell gene expression'},
        ),
    ]
