# Generated by Django 5.2.8 on 2025-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_unmanage_singlecellgeneexpression'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genemodule',
            index=models.Index(fields=['name'], name='genemodule_name_idx')
        ),
        migrations.AddIndex(
            model_name='metacelltype',
            index=models.Index(fields=['name'], name='metacelltype_name_idx'),
        ),
    ]
