# Generated by Django 5.2.8 on 2025-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_unmanage_singlecellgeneexpression'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metacelltype',
            name='metacelltype_name_idx',
        ),
        migrations.AddIndex(
            model_name='metacelltype',
            index=models.Index(fields=['dataset', 'name'], name='app_metacel_dataset_and_name_idx'),
        ),
    ]

