# Generated by Django 5.2.8 on 2025-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_unmanage_singlecellgeneexpression'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genemodule',
            index=models.Index(fields=['name'], name='app_genemodule_name_idx'),
        ),
        migrations.AddIndex(
            model_name='metacelltype',
            index=models.Index(fields=['dataset', 'name'], name='app_metacel_dataset_c33ca1_idx'),
        ),
    ]
