# Generated by Django 5.2.8 on 2025-12-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Publication title.', max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated list of authors.')),
                ('year', models.PositiveIntegerField(help_text='Year of publication.')),
                ('journal', models.CharField(help_text='Journal.', max_length=255)),
                ('doi', models.CharField(help_text='DOI (Digital Object Identifier).', max_length=255, unique=True)),
                ('pmid', models.CharField(help_text='PubMed identifier.', max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='source',
        ),
        migrations.AddField(
            model_name='dataset',
            name='publication',
            field=models.ForeignKey(help_text='Dataset publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.publication'),
        ),
    ]
