# Generated by Django 5.2.9 on 2026-01-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('app', '0007_alter_gene_options_alter_genelist_options')]

    dependencies = [
        ('app', '0006_add_publications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['species', 'name']},
        ),
        migrations.AlterModelOptions(
            name='genelist',
            options={'ordering': ['name']},
        ),
    ]
