# Generated by Django 5.2.10 on 2026-01-20 13:28

from django.db import migrations, models
from app.models import Species, Dataset


def populate_slugs(apps, schema_editor):
    """Generate slugs in existing data."""
    for s in Species.objects.all():
        s.save()

    for d in Dataset.objects.all():
        d.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs),

    ]
