# Generated by Django 5.2.10 on 2026-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
