# Generated by Django 5.2.10 on 2026-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g., 2026.02.11', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Notes on changes.')),
                ('populated_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this data version was populated in the database.')),
            ],
            options={
                'verbose_name': 'Database Version Log',
                'ordering': ['-populated_at'],
            },
        ),
    ]
