# Generated by Django 5.2.6 on 2025-11-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dataset_options_alter_domain_options_and_more_squashed_0009_alter_datasetqualitycontrol_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genemodule',
            unique_together={('name', 'gene', 'dataset')},
        ),
    ]
