# Generated by Django 5.2.10 on 2026-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dbversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbversion',
            name='commit',
            field=models.CharField(help_text='Git commit hash associated with this change.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dbversion',
            name='populated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the data was added.'),
        ),
        migrations.AlterField(
            model_name='dbversion',
            name='version',
            field=models.CharField(help_text='e.g., 2026.02.11', max_length=50, null=True),
        ),
    ]
