# Generated by Django 5.2.8 on 2025-11-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dataset_options_alter_domain_options_and_more_squashed_0009_alter_datasetqualitycontrol_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genemodule',
            unique_together={('name', 'gene', 'dataset')},
        ),
        migrations.AddField(
            model_name='genemodule',
            name='eigenvalue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='genemodule',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='GeneModuleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.gene')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genemodule')),
            ],
            options={
                'unique_together': {('gene', 'module')},
                'ordering': ['module__dataset__order', 'module__name'],
            },
        ),
        migrations.RemoveField(
            model_name='genemodule',
            name='eigenvalue',
        ),
        migrations.RemoveField(
            model_name='genemodule',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='genemodule',
            name='membership_score',
        ),
        migrations.AddField(
            model_name='genemodule',
            name='genes',
            field=models.ManyToManyField(through='app.GeneModuleMembership', to='app.gene'),
        ),
        migrations.CreateModel(
            name='GeneModuleEigenvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigenvalue', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('metacell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.metacell')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genemodule')),
            ],
            options={
                'unique_together': {('module', 'metacell')},
            },
        ),
        migrations.AddField(
            model_name='genemodule',
            name='eigenvalues',
            field=models.ManyToManyField(through='app.GeneModuleEigenvalue', to='app.metacell'),
        ),
        migrations.AlterField(
            model_name='genemodulemembership',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='app.genemodule'),
        ),
        migrations.AlterModelOptions(
            name='genemodule',
            options={},
        ),
    ]
