# Generated by Django 5.2.10 on 2026-02-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_improve_dbversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genemodule',
            options={'ordering': ['dataset', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='genemodule',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='GeneModuleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.gene')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='app.genemodule')),
            ],
            options={
                'ordering': ['module__dataset__order', 'module__name'],
                'unique_together': {('gene', 'module')},
            },
        ),
        migrations.AddField(
            model_name='genemodule',
            name='genes',
            field=models.ManyToManyField(through='app.GeneModuleMembership', to='app.gene'),
        ),
        migrations.RemoveField(
            model_name='genemodule',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='genemodule',
            name='membership_score',
        ),
        migrations.CreateModel(
            name='GeneModuleEigenvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigenvalue', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('metacell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.metacell')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eigenvalues', to='app.genemodule')),
            ],
            options={
                'unique_together': {('module', 'metacell')},
            },
        ),
    ]
