# Generated by Django 5.2.11 on 2026-03-02 14:22

import django.db.models.deletion
from django.db import migrations, models


def move_orthogroup_names(apps, schema_editor):
    Ortholog = apps.get_model('app', 'Ortholog')
    Orthogroup = apps.get_model('app', 'Orthogroup')

    # Get unique orthogroup names from orthologs
    orthogroup_names = set(Ortholog.objects.values_list('orthogroup', flat=True))
    sorted_orthogroup_names = sorted(orthogroup_names, key=lambda x: int(x.split('_')[1]))

    # Create Orthogroup entries
    orthogroups = [Orthogroup(name=n) for n in sorted_orthogroup_names]
    Orthogroup.objects.bulk_create(orthogroups, ignore_conflicts=True)

    # Get IDs for each Orthogroup
    orthogroup_map = dict(Orthogroup.objects.values_list('name', 'id'))

    # Update orthologs to use the orthogroup ID
    for ortholog in Ortholog.objects.all():
        ortholog.orthogroup = orthogroup_map[ortholog.orthogroup]
        ortholog.save(update_fields=['orthogroup'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_improve_gene_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthogroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genes', models.ManyToManyField(related_name='orthogroups', through='app.Ortholog', to='app.gene')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(move_orthogroup_names),
        migrations.AlterField(
            model_name='ortholog',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthologs', to='app.gene'),
        ),
        migrations.AlterField(
            model_name='ortholog',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthologs', to='app.species'),
        ),
        migrations.AlterField(
            model_name='ortholog',
            name='orthogroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthologs', to='app.orthogroup'),
        ),
    ]
