# Generated by Django 5.2.13 on 2026-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_improve_orthologs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfile',
            name='type',
            field=models.CharField(choices=[('Proteome', 'Proteome'), ('DIAMOND', 'DIAMOND database'), ('eggnog-mapper', 'eggNOG-mapper functional annotation')], help_text='File type.', max_length=255),
        ),
    ]
