# Generated by Django 5.2.13 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_improve_orthologs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('checksum', models.CharField(editable=False, help_text='SHA256 digest.', max_length=64)),
                ('file', models.FileField(help_text='File.', upload_to='')),
                ('type', models.CharField(choices=[('go-basic-obo', 'Gene Ontology OBO file (basic version)')], help_text='File type.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='speciesfile',
            name='type',
            field=models.CharField(choices=[('Proteome', 'Proteome'), ('DIAMOND', 'DIAMOND database'), ('eggnog-mapper', 'eggNOG-mapper functional annotation')], help_text='File type.', max_length=255),
        ),
    ]
