# Generated by Django 5.2.15 on 2026-07-13 14:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_go_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetacellTypeSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samap_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('samap_gene_pairs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), blank=True, default=list, size=None)),
                ('aucell_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aucell_gene_pairs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), blank=True, default=list, size=None)),
                ('pesci_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pesci_gene_pairs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), blank=True, default=list, size=None)),
                ('metacelltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.metacelltype')),
                ('metacelltype2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='app.metacelltype')),
            ],
            options={
                'verbose_name': 'Metacell type similarity',
                'verbose_name_plural': 'Metacell type similarity',
                'unique_together': {('metacelltype', 'metacelltype2')},
            },
        ),
        migrations.DeleteModel(
            name='SAMap',
        ),
    ]
