# Generated by Django 5.2.15 on 2026-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_mge_covering_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfile',
            name='type',
            field=models.CharField(choices=[('go-basic-obo', 'Gene Ontology OBO file (basic version)'), ('tree-of-life', 'Tree of Life Newick file')], help_text='File type.', max_length=255),
        ),
    ]
