# Generated by Django 5.2.16 on 2026-07-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionConservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conservation_score', models.FloatField(help_text='Expression conservation score.')),
                ('is_one_to_one', models.BooleanField(default=True, help_text='Whether the ortholog pair is one-to-one.')),
                ('dataset', models.ForeignKey(help_text='Dataset for the first gene.', on_delete=django.db.models.deletion.CASCADE, related_name='conservations_as', to='app.dataset')),
                ('dataset2', models.ForeignKey(help_text='Dataset for the second gene.', on_delete=django.db.models.deletion.CASCADE, related_name='conservations2_as', to='app.dataset')),
                ('gene', models.ForeignKey(help_text='First gene in the ortholog pair.', on_delete=django.db.models.deletion.CASCADE, related_name='conservations_as', to='app.gene')),
                ('gene2', models.ForeignKey(help_text='Second gene in the ortholog pair.', on_delete=django.db.models.deletion.CASCADE, related_name='conservations2_as', to='app.gene')),
                ('orthogroup', models.ForeignKey(help_text='Orthogroup the conservation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='conservations', to='app.orthogroup')),
            ],
            options={
                'verbose_name': 'Expression conservation score',
                'verbose_name_plural': 'Expression conservation scores',
                'ordering': ['orthogroup'],
                'indexes': [models.Index(fields=['gene'], name='app_express_gene_id_56fdb9_idx'), models.Index(fields=['gene2'], name='app_express_gene2_i_4c8566_idx')],
                'unique_together': {('gene', 'gene2', 'dataset', 'dataset2')},
            },
        ),
    ]
