# Generated by Django 5.2.15 on 2026-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_expression_conservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacell',
            name='cytotrace',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metacell',
            name='median_umis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='singlecell',
            name='cytotrace',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='singlecell',
            name='median_umis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metacell',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metacell',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
