# Generated by Django 5.2.17 on 2026-08-18 10:08

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cytotrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='internal_id',
            field=models.CharField(blank=True, help_text='Internal identifier.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='platform',
            field=models.CharField(blank=True, help_text='Sequencing platform.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='symbol',
            field=models.CharField(blank=True, help_text='Gene symbol.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('color', colorfield.fields.ColorField(default='#AAAAAA', image_field=None, max_length=25, samples=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_types', to='app.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'name'], name='app_celltyp_dataset_423256_idx')],
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.AddField(
            model_name='singlecell',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.celltype'),
        ),
        migrations.RemoveField(
            model_name='metacell',
            name='links',
        ),
        migrations.CreateModel(
            name='MetacellEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metacell_edges', to='app.dataset')),
                ('metacell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edges', to='app.metacell')),
                ('metacell2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edges', to='app.metacell')),
            ],
        ),
        migrations.AddField(
            model_name='metacell',
            name='edges',
            field=models.ManyToManyField(through='app.MetacellEdge', to='app.metacell'),
        ),
        migrations.DeleteModel(
            name='MetacellLink',
        ),
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='metacell',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='metacelltypesimilarity',
            old_name='aucell_score',
            new_name='aucell_1to2',
        ),
        migrations.AddField(
            model_name='metacelltypesimilarity',
            name='aucell_2to1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
