# Generated by Django 5.2.17 on 2026-10-08 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rc_release_fixes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domain',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='domain_name_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'description'], name='gene_name_desc_trgm_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
