---
rules:
    unpinned-uses:
        config:
            policies:
                "*": ref-pin
    secrets-outside-env:
        config:
            allow:
                - DOCKERHUB_USERNAME
                - DOCKERHUB_PASSWORD
