# Generated by Django 5.1.3 on 2024-11-22 16:00

import colorfield.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('id', models.BigIntegerField(default=2222, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Metacell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('color', colorfield.fields.ColorField(default='#AAAAAA', image_field=None, max_length=25, samples=None)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'unique_together': {('name', 'species')},
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'unique_together': {('name', 'species')},
            },
        ),
        migrations.CreateModel(
            name='SingleCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('metacell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.metacell')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'unique_together': {('name', 'species')},
            },
        ),
        migrations.CreateModel(
            name='MetacellLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metacell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metacell', to='web_app.metacell')),
                ('metacell2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metacell2', to='web_app.metacell')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'unique_together': {('species', 'metacell', 'metacell2')},
            },
        ),
        migrations.CreateModel(
            name='MetacellGeneExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.gene')),
                ('metacell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.metacell')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'verbose_name': 'metacell gene expression',
                'verbose_name_plural': 'metacell gene expression',
                'unique_together': {('gene', 'metacell', 'species')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.species')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'meta',
                'unique_together': {('species', 'key', 'value')},
            },
        ),
    ]
