# Generated by Django 5.1.3 on 2024-12-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metacellgeneexpression',
            old_name='value',
            new_name='fold_change',
        ),
    ]
