# Generated by Django 5.1.3 on 2024-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_value_metacellgeneexpression_fold_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacellgeneexpression',
            name='umifraq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metacellgeneexpression',
            name='fold_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
