# Generated by Django 5.1.3 on 2024-12-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_metacellgeneexpression_umifraq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metacellgeneexpression',
            old_name='umifraq',
            new_name='umifrac',
        ),
    ]
