# Generated by Django 5.1.3 on 2024-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_rename_umifraq_metacellgeneexpression_umifrac'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacellgeneexpression',
            name='umiraw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
