# Generated by Django 5.1.3 on 2024-12-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_metacellgeneexpression_umiraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metacellgeneexpression',
            old_name='umiraw',
            new_name='umi_raw',
        ),
    ]
