name: Publish Docker image
on:
    workflow_dispatch:
    push:
        branches:
            - main
        tags:
            - "v*"

permissions:
    packages: write
    contents: read

jobs:
    push_to_registries:
        name: Push Docker image to multiple registries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  submodules: recursive
                  persist-credentials: false

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Tune QEMU
              run: |
                  docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-* && docker run --privileged --rm tonistiigi/binfmt --install all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  labels: |
                      org.opencontainers.image.title=BCA Website
                      org.opencontainers.image.description=Biodiversity Cell Atlas website and data portal
                      org.opencontainers.image.vendor=CRG
                      org.opencontainers.image.authors="Biodiversity Cell Atlas <bca@biodiversitycellatlas.org>"
                      org.opencontainers.image.licenses=Apache-2.0
                      org.opencontainers.image.version=${{ github.ref_name }}
                      org.opencontainers.image.revision=${{ github.sha }}
                      org.opencontainers.image.url=https://biodiversitycellatlas.org
                      org.opencontainers.image.source=${{ github.repositoryUrl }}
                  images: |
                      ghcr.io/${{ github.repository }}

            - name: Log in to GitHub Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ${{ steps.meta.outputs.tags }}
                  labels: |
                      ${{ steps.meta.outputs.labels }}
