---
name: Docker security scan

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        # Run every Wednesday at 7h
        - cron: "0 7 * * 3"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    trivy:
        name: Trivy
        runs-on: ubuntu-latest

        permissions:
            contents: read
            security-events: write # upload SARIF results

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  persist-credentials: false

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: docker build -t bca-website:ci .

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: bca-website:ci
                  format: "template"
                  template: "@/contrib/sarif.tpl"
                  output: "trivy-results.sarif"
                  severity: "CRITICAL,HIGH"

            - name: Upload results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: "trivy-results.sarif"
