---
name: Python security scan

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        # Run every Wednesday at 7h
        - cron: "0 7 * * 3"
    workflow_dispatch:

permissions:
    security-events: write

jobs:
    bandit:
        name: Bandit
        runs-on: ubuntu-latest
        steps:
            - name: Run Bandit and upload results to GitHub Security tab
              uses: PyCQA/bandit-action@v1
              with:
                  exclude: ".git,./scripts,__pycache__"
