name: Python security scan

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        # Run every Wednesday at 7h
        - cron: '0 7 * * 3'
    workflow_dispatch:

permissions:
  contents: read

jobs:
    bandit:
        name: Bandit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Install dependencies
              run: pip install bandit -r requirements.txt

            - name: Run Bandit
              run: bandit -r . -x ./scripts
